{lib}: {
  username = "cong";
  userfullname = "CCCC-L";
  useremail = "nageniaiwome@qq.com";
  
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....tKjZLp/oUr8m.LVn5zinX.$zqFK/PFPtLbG.hg4leatgFkS1p6czrPIyatJpEpjql0";
}
