[manager]
prepend_keymap = [
  { on = "n", run = "create", desc = "Create a file (ends with / for directories)" },
  { on = "<S-n>", run = "create --dir", desc = "Create a file (ends with / for directories)" },
  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
]
